// VERIFAI Command Center — the procurement officer's overview.
import { Link } from "react-router-dom";
import {
  AlertTriangle,
  ArrowRight,
  FileStack,
  FolderOpen,
  Info,
  PlayCircle,
  RefreshCw,
  ShieldCheck,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { DistributionBar } from "@/components/verifai/distribution-bar";
import { EmptyState } from "@/components/verifai/empty-state";
import { PageHeader } from "@/components/verifai/page-header";
import { Pill, ResultBadge, RiskBadge } from "@/components/verifai/result-badge";
import { StatTile } from "@/components/verifai/stat-tile";
import { PrototypeNotice, SyntheticNotice } from "@/components/verifai/synthetic-notice";
import { EXPECTED_IMPACT_NOTICE, SCORE_NOTICE } from "@/lib/verifai/labels";
import { formatRelative } from "@/lib/verifai/format";
import { useDashboardData } from "./use-dashboard-data";

const DashboardPage = () => {
  const data = useDashboardData();

  if (data.isError) {
    return (
      <Card className="border-border shadow-panel">
        <CardContent className="p-6">
          <EmptyState
            icon={AlertTriangle}
            title="The Command Center could not load its data"
            description={data.error?.message ?? "The backend did not return the tender records."}
            action={
              <Button size="sm" onClick={data.refetch}>
                <RefreshCw aria-hidden />
                Retry
              </Button>
            }
          />
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Command Center"
        title="VERIFAI Command Center"
        description="AI-assisted bid compliance verification for GeM procurement. Every result carries the evidence behind it, and the final decision stays with the Procurement Officer."
        actions={
          <>
            <Button size="sm" variant="outline" asChild>
              <Link to="/tenders">
                <FolderOpen aria-hidden />
                Open tenders
              </Link>
            </Button>
            {data.demoCases[0] ? (
              <Button size="sm" asChild>
                <Link to={`/review/${data.demoCases[0].submission_id}`}>
                  <PlayCircle aria-hidden />
                  Open primary demo review
                </Link>
              </Button>
            ) : null}
          </>
        }
      />

      {data.demoEnabled ? (
        <div className="flex flex-col gap-2 rounded-md border border-info-border bg-info-subtle px-4 py-3 text-sm text-info sm:flex-row sm:items-center sm:justify-between">
          <p className="flex items-start gap-2">
            <Info className="mt-0.5 h-4 w-4 shrink-0" aria-hidden />
            <span>
              <span className="label-mono mr-1">DEMO MODE</span>
              {data.tenderCount} tenders, {data.bidderCount} bidders, {data.recentReviews.length} verified bids, evidence
              records, simulated verification results and an audit trail are preloaded.
            </span>
          </p>
          <Button size="sm" variant="outline" asChild className="shrink-0">
            <Link to="/settings">
              Demo settings
              <ArrowRight aria-hidden />
            </Link>
          </Button>
        </div>
      ) : null}

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatTile
          label="Active tenders"
          value={data.activeTenders}
          hint="Published and open for bids"
          tone="info"
          icon={FolderOpen}
          loading={data.isLoading}
        />
        <StatTile
          label="Bids under review"
          value={data.bidsUnderReview}
          hint="Awaiting a recorded officer decision"
          tone="review"
          icon={FileStack}
          loading={data.isLoading}
        />
        <StatTile
          label="Compliance reviews"
          value={data.reviewsCompleted}
          hint="Evidence records generated by the engine"
          tone="pass"
          icon={ShieldCheck}
          loading={data.isLoading}
        />
        <StatTile
          label="High risk cases"
          value={data.highRiskCases}
          hint="Mandatory failure or unresolved verification"
          tone="fail"
          icon={AlertTriangle}
          loading={data.isLoading}
        />
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <Card className="border-border shadow-panel lg:col-span-2">
          <CardHeader className="gap-1.5 pb-3">
            <CardTitle className="text-base">Recent bid reviews</CardTitle>
            <CardDescription className="text-xs">
              Latest verification results. Open any bid to inspect its Evidence Trace.
            </CardDescription>
          </CardHeader>
          <CardContent className="p-0">
            {data.recentReviews.length === 0 ? (
              <div className="p-5">
                <EmptyState
                  icon={ShieldCheck}
                  title="No bid reviews yet"
                  description="Verification results appear here once the compliance engine has produced evidence for a submission."
                />
              </div>
            ) : (
              <Table dense>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead className="pl-5">Bid</TableHead>
                    <TableHead>Bidder</TableHead>
                    <TableHead className="text-right">Score</TableHead>
                    <TableHead>Risk</TableHead>
                    <TableHead>Result</TableHead>
                    <TableHead className="pr-5 text-right">Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.recentReviews.map(({ submission, tender, bidder }) => (
                    <TableRow key={submission.id}>
                      <TableCell className="whitespace-nowrap pl-5">
                        <p className="font-medium text-foreground">{submission.id}</p>
                        <p className="text-xs text-muted-foreground">{formatRelative(submission.verified_at)}</p>
                      </TableCell>
                      <TableCell className="max-w-[240px]">
                        <p className="truncate text-sm text-foreground">{bidder?.name ?? "—"}</p>
                        <p className="truncate text-xs text-muted-foreground">{tender?.name ?? "—"}</p>
                      </TableCell>
                      <TableCell className="whitespace-nowrap text-right font-semibold tabular-nums text-foreground">
                        {submission.compliance_score === null ? "—" : `${submission.compliance_score}%`}
                      </TableCell>
                      <TableCell>
                        {submission.risk_level ? <RiskBadge risk={submission.risk_level} /> : <Pill tone="neutral">—</Pill>}
                      </TableCell>
                      <TableCell>
                        {submission.overall_status ? (
                          <ResultBadge result={submission.overall_status} />
                        ) : (
                          <Pill tone="neutral">PENDING</Pill>
                        )}
                      </TableCell>
                      <TableCell className="whitespace-nowrap pr-5 text-right">
                        <Button variant="ghost" size="sm" asChild>
                          <Link to={`/review/${submission.id}`}>
                            Review
                            <ArrowRight aria-hidden />
                          </Link>
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>

        <Card className="border-border shadow-panel">
          <CardHeader className="gap-1.5 pb-3">
            <CardTitle className="text-base">Demo cases</CardTitle>
            <CardDescription className="text-xs">
              Preloaded scenarios that show PASS, FAIL and REVIEW end to end.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {data.demoCases.length === 0 ? (
              <EmptyState
                icon={PlayCircle}
                title="No demo cases configured"
                description="Demo cases are stored with the project settings."
              />
            ) : (
              data.demoCases.map((demoCase, index) => (
                <Link
                  key={demoCase.submission_id}
                  to={`/review/${demoCase.submission_id}`}
                  className="block rounded-md border border-border p-3 transition-colors hover:bg-muted/60"
                >
                  <p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                    {index === 0 ? "Primary demo" : `Demo ${index + 1}`}
                    <span className="label-mono rounded border border-border px-1.5 py-0.5">
                      {demoCase.submission_id}
                    </span>
                  </p>
                  <p className="mt-1.5 text-sm font-medium text-foreground">{demoCase.title}</p>
                  <p className="mt-1 text-xs text-muted-foreground">{demoCase.expected}</p>
                </Link>
              ))
            )}
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <Card className="border-border shadow-panel lg:col-span-2">
          <CardHeader className="gap-1.5 pb-3">
            <CardTitle className="text-base">Recent tenders</CardTitle>
            <CardDescription className="text-xs">
              Requirement sets currently driving bid verification.
            </CardDescription>
          </CardHeader>
          <CardContent className="p-0">
            {data.recentTenders.length === 0 ? (
              <div className="p-5">
                <EmptyState icon={FolderOpen} title="No tenders on record" />
              </div>
            ) : (
              <Table dense>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead className="pl-5">Tender ID</TableHead>
                    <TableHead>Tender name</TableHead>
                    <TableHead className="text-right">Requirements</TableHead>
                    <TableHead className="text-right">Bids</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="pr-5 text-right">Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.recentTenders.map(({ tender, requirementCount, bidCount }) => (
                    <TableRow key={tender.id}>
                      <TableCell className="whitespace-nowrap pl-5 font-medium text-foreground">
                        {tender.id}
                      </TableCell>
                      <TableCell className="max-w-[260px]">
                        <p className="truncate text-sm text-foreground">{tender.name}</p>
                        <p className="truncate text-xs text-muted-foreground">
                          {tender.department} · updated {formatRelative(tender.updated_at)}
                        </p>
                      </TableCell>
                      <TableCell className="text-right tabular-nums text-foreground">{requirementCount}</TableCell>
                      <TableCell className="text-right tabular-nums text-foreground">{bidCount}</TableCell>
                      <TableCell>
                        <Pill tone={tender.status === "ACTIVE" ? "pass" : "neutral"}>{tender.status}</Pill>
                      </TableCell>
                      <TableCell className="whitespace-nowrap pr-5 text-right">
                        <Button variant="ghost" size="sm" asChild>
                          <Link to={`/tenders/${tender.id}`}>
                            Open
                            <ArrowRight aria-hidden />
                          </Link>
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>

        <Card className="border-border shadow-panel">
          <CardHeader className="gap-1.5 pb-3">
            <CardTitle className="text-base">Result distribution</CardTitle>
            <CardDescription className="text-xs">
              Across {data.reviewsCompleted} verified bid{data.reviewsCompleted === 1 ? "" : "s"}.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <DistributionBar
              title="Compliance status"
              segments={data.statusSegments}
              emptyLabel="No verified bids yet, so there is no distribution to show."
            />
            <DistributionBar
              title="Risk level"
              segments={data.riskSegments}
              emptyLabel="No verified bids yet, so there is no risk distribution to show."
            />
            <p className="border-t border-border pt-3 text-[11px] leading-relaxed text-muted-foreground">
              {SCORE_NOTICE}
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="space-y-3">
        <SyntheticNotice />
        <PrototypeNotice />
        <p className="text-[11px] leading-relaxed text-muted-foreground">
          {EXPECTED_IMPACT_NOTICE} Faster first-pass review of bidder documents, with every automated result
          traceable to its source page and rule. No measured savings or accuracy figures are claimed by this
          prototype.
        </p>
      </div>
    </div>
  );
};

export default DashboardPage;
